"""
Deterministic "why is this an attack" evidence.

Shared by the event-detail API and the high-risk alert email so the same
payload-grounded justification appears in both. This is NOT generated by the
language model: it matches the detection rule against the raw log sample and
pulls out the exact suspicious bytes, so the justification is always grounded
in real evidence and cannot be talked out of by a prompt-injection payload.
"""
import re
from urllib.parse import unquote

# (attack_type, regex, plain-English reason, fallback MITRE technique)
_EVIDENCE = [
    ("SQL Injection",
     re.compile(r"union\s+select|or\s+1\s*=\s*1|information_schema|'\s*or\s|--\s|sleep\(|benchmark\(", re.I),
     "The request injects SQL into a query parameter (e.g. a UNION SELECT) to read or alter the database directly. Normal use never sends SQL keywords in a URL.",
     "T1190"),
    ("Cross-Site Scripting",
     re.compile(r"<script|onerror\s*=|onload\s*=|<img|<svg|javascript:|alert\(", re.I),
     "The request injects HTML/JavaScript (e.g. a <script> tag) so it runs in another user's browser - a reflected cross-site-scripting attempt. Legitimate input is plain text.",
     "T1059.007"),
    ("Command Injection",
     re.compile(r";\s*id\b|\|\s*whoami|&&\s*uname|;\s*cat\s+/etc|`[^`]+`|\$\(", re.I),
     "The request appends shell metacharacters (e.g. ;id, |whoami) to run operating-system commands on the server - a command-injection attempt.",
     "T1059"),
    ("File Inclusion",
     re.compile(r"\.\./|\.\.%2f|\.\.\\|/etc/passwd|\.\.//", re.I),
     "The request uses path traversal (e.g. ../../etc/passwd) to read files outside the web root - a file-inclusion / path-traversal attempt.",
     "T1083"),
    ("SSH Brute Force",
     re.compile(r"failed password|authentication failure|invalid user", re.I),
     "Repeated failed SSH logins from this source in a short burst - a password brute-force attempt. A real user does not fail this many times.",
     "T1110"),
    ("Port Scan",
     re.compile(r"PORTSCAN|nmap|masscan|SYN\b", re.I),
     "Rapid connection attempts across many ports (a SYN sweep) - a port scan mapping the host's open services. Normal clients contact one service.",
     "T1046"),
]


def attack_evidence(attack_type, raw_logs, rule=None, mitre=None, log_count=None):
    """Return the evidence dict for an event given its attack type and raw log
    sample: {attack_type, rule, signature, reason, mitre, log_count}.
    `signature` is the exact suspicious token pulled from the logs, or None."""
    raw = "\n".join(str(x) for x in (raw_logs or []))
    # Apache logs percent-encode payloads (UNION%20SELECT), so match the decoded
    # form too; the snippet is taken from this combined, human-readable text.
    text = raw + "\n" + unquote(raw)
    atype = (attack_type or "").strip().lower()
    for name, rx, reason, mitre_default in _EVIDENCE:
        nm = name.lower()
        if (atype and (nm in atype or atype in nm)) or (not atype and rx.search(text)):
            m = rx.search(text)
            snippet = None
            if m:
                a = max(0, m.start() - 30)
                b = min(len(text), m.end() + 30)
                snippet = text[a:b].replace("\n", " ").strip()
            return {
                "attack_type": name,
                "rule": rule or name,
                "signature": snippet,
                # the exact token the rule matched (e.g. "Failed password",
                # "UNION SELECT") so the UI can highlight it inside the log lines
                "match": m.group(0) if m else None,
                "reason": reason,
                "mitre": (mitre or [mitre_default])[:1],
                "log_count": log_count,
            }
    return {
        "attack_type": attack_type or "Unclassified",
        "rule": rule,
        "signature": None,
        "match": None,
        "reason": "This event matched a detection rule, but no specific payload signature could be extracted automatically - review the raw log sample to confirm.",
        "mitre": (mitre or [])[:1],
        "log_count": log_count,
    }


_WEB_RE = re.compile(r'"?(GET|POST|HEAD|PUT|DELETE)\s+(\S+)')
_IP_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")


def _line_meaning(s, low):
    """Plain-English explanation of a single raw log line."""
    ipm = _IP_RE.search(s)
    ips = ipm.group(0) if ipm else None
    if "failed password" in low or "authentication failure" in low or "invalid user" in low:
        return ("SSH log: a failed login attempt" + (f" from {ips}" if ips else "")
                + " - one try in the password brute-force.")
    if "portscan" in low or ("kernel:" in low and ("syn" in low or "dpt=" in low or "proto=tcp" in low)):
        return ("Firewall log: a packet the target's iptables flagged as part of a port scan "
                "(many ports contacted in quick succession).")
    if any(t in low for t in ("mysqli_sql_exception", "value is out of range",
                              "you have an error in your sql", "sql syntax",
                              "elt(", "extractvalue", "updatexml", "union select")):
        return ("Database error caused by the injection: the attacker used an error-based SQL "
                "injection - forcing MySQL to overflow/error so it leaks the queried data inside "
                "the error message. The error itself proves the injection reached and ran in the "
                "database.")
    if "php:error" in low or "php fatal" in low:
        return "PHP application-error log: the injected input made the web application throw an error."
    wm = _WEB_RE.search(s)
    if wm:
        method, path = wm.group(1), wm.group(2)
        payload = any(t in low for t in ("union", "select", "<script", "onerror",
                                         "../", "etc/passwd", ";id", "|whoami", "%2f", "alert("))
        return (f"Web access log: an HTTP {method} request to "
                f"`{path[:70]}{'...' if len(path) > 70 else ''}`"
                + (" carrying the attack payload in the query string." if payload
                   else " on the targeted page."))
    if "sshd" in low:
        return "SSH daemon log line."
    return "A raw log line recorded on the monitored host."


def annotate_logs(raw_logs, limit=60):
    """Explain what each KIND of raw log line represents, de-duplicated: lines
    that share the same explanation are grouped so the analyst sees the distinct
    pieces of evidence rather than N identical rows. Returns
    [(representative_line, meaning, count)]."""
    groups, order = {}, []
    for line in (raw_logs or [])[:limit]:
        s = str(line)
        meaning = _line_meaning(s, s.lower())
        if meaning not in groups:
            groups[meaning] = [s, 0]
            order.append(meaning)
        groups[meaning][1] += 1
    return [(groups[m][0], m, groups[m][1]) for m in order]
